document.write (typeof "word" +"<br>");
document.write (typeof 5 + "<br>");
document.write ("five"+5+"<br>");
document.write(2E310+"<br>");
document.write("after dividing a number by 0 = "+ (5/0) + "<br>");
document.write("Negative infinity : "+ -2E310);
document.write("<br> Print whether the number '8' is greater than '3' or not : "+(8>3));
document.write("<br> Print whether the number '4' is an odd number : "+(4%2 == 1));
console.log("The sum of 2 and 3 is : "+ (2+3));
console.log("The number 21 is less than 12 - true or false : "+ (21<12));
document.write("<br> checking 10 is equal to 10 : "+ (10==10));
x=12;
y="12";
document.write("<br>checking the === functionality using 12 and \"12\" : "+ (x === y));
document.write("<br>checking the === functionality using x and 12 : "+ (x === 12));
document.write("<br>checking the === functionality using 11 and \"12\" : "+ (y === 11));
document.write("<br>checking the === functionality using x and 15 : "+ (x === 15));
document.write("<br>checking AND (5>2 && 10>4): "+ (5>2 && 10>4));
document.write("<br>checking AND (5>10 && 10>4): "+ (5>10 && 10>4));
document.write("<br>checking OR (5>10 || 10>4): "+ (5>10 || 10>4));
document.write("<br>checking OR (5>10 || 10>20): "+ (5>10 || 10>20));